lans = [["中文", "Chinese", "zh"],
        ["英文", "English", "en"],
        ["阿尔巴尼亚语", "Albanian", "sq"],
        ["阿拉伯语", "Arabic", "ar"],
        ["阿姆哈拉语", "Amharic", "am"],
        ["阿丘雅语", "Achuar", "acu"],
        ["阿瓜鲁纳语", "Aguaruna", "agr"],
        ["阿卡瓦伊语", "Akawaio", "ake"],
        ["阿穆斯戈语", "Amuzgo", "amu"],
        ["阿塞拜疆语", "Azerbaijani", "az"],
        ["爱尔兰语", "Irish", "ga"],
        ["爱沙尼亚语", "Estonian", "et"],
        ["埃维语", "Ewe", "ee"],
        ["奥吉布瓦语", "Ojibwa", "ojb"],
        ["奥罗莫语", "Oromoo", "om"],
        ["奥利亚语", "Oriya", "or"],
        ["奥赛梯语", "Ossetic", "os"],
        ["巴布亚皮钦语", "Tok Pisin", "tpi"],
        ["巴拉萨纳语", "Barasana", "bsn"],
        ["巴什基尔语", "Bashkir", "ba"],
        ["巴斯克语", "Basque", "eu"],
        ["白俄罗斯语", "Belarusian", "be"],
        ["白苗文", "Hmong", "mww"],
        ["柏柏尔语", "Berber", "ber"],
        ["保加利亚语", "Bulgarian", "bg"],
        ["冰岛语", "Icelandic", "is"],
        ["比斯拉马语", "Bislama", "bi"],
        ["别姆巴语", "Bemba", "bem"],
        ["波兰语", "Polish", "pl"],
        ["波斯尼亚语", "Bosnian", "bs"],
        ["波斯语", "Persian", "fa"],
        ["波塔瓦托米语", "Potawatomi", "pot"],
        ["布列塔尼语", "Brezhoneg", "br"],
        ["卡拜尔语", "Kabyle", "kab"],
        ["卡韦卡尔语", "Cabecar", "cjp"],
        ["卡克奇克尔语", "Cakchiquel", "cak"],
        ["查莫罗语", "Chamorro", "cha"],
        ["楚瓦什语", "Chuvash", "cv"],
        ["茨瓦纳语", "Tswana", "tn"],
        ["聪加语", "Xitsonga", "ts"],
        ["鞑靼语", "Tatar", "tt"],
        ["丹麦语", "Danish", "da"],
        ["德语", "German", "de"],
        ["德顿语", "Tetun", "tet"],
        ["迪维希语", "Divehi", "dv"],
        ["丁卡语", "Dinka", "dik"],
        ["俄语", "Russian", "ru"],
        ["恩都卡语", "Ndyuka", "djk"],
        ["法语", "French", "fr"],
        ["法罗语", "Faroese", "fo"],
        ["菲律宾语", "Filipino", "fil"],
        ["斐济语", "Fijian", "fj"],
        ["芬兰语", "Finnish", "fi"],
        ["高棉语", "Khmer", "km"],
        ["盖丘亚语", "Quichua", "quw"],
        ["刚果语", "Kikongo", "kg"],
        ["弗里西语", "Frisian", "fy"],
        ["格鲁吉亚语", "Georgian", "jy"],
        ["古吉拉特语", "Gujarati", "gu"],
        ["哈萨克语", "Kazakh", "ka"],
        ["哈萨克语(西里尔)", "Kazakh(Cyrillic)", "kk"],
        ["海地克里奥尔语", "Haitian Creole", "ht"],
        ["韩语", "Korean", "ko"],
        ["豪萨语", "Hausa", "ha"],
        ["荷兰语", "Dutch", "nl"],
        ["黑山语", "Montenegro", "me"],
        ["吉尔吉斯语", "Kyrgyz", "ky"],
        ["基切语", "Kiche", "quc"],
        ["加莱拉语", "Galela", "gbi"],
        ["加利西亚语", "Galician", "gl"],
        ["加泰罗尼亚语", "Catalan", "ca"],
        ["捷克语", "Czech", "cs"],
        ["卡纳达语", "Kannada", "kn"],
        ["凯克其语", "Qeqchi", "kek"],
        ["坎帕语", "Campa", "cni"],
        ["科普特语", "Coptic", "cop"],
        ["科奇语", "Camsa", "kbh"],
        ["科西嘉语", "Corsican", "co"],
        ["克雷塔罗奥托米语", "Queretaro Otomi", "otq"],
        ["克罗地亚语", "Croatian", "hr"],
        ["库尔德语", "Kurdish", "ku"],
        ["拉丁语", "Latin", "la"],
        ["拉脱维亚语", "Latvian", "lv"],
        ["老挝语", "Lao", "lo"],
        ["隆迪语", "Kirundi", "rn"],
        ["立陶宛语", "Lithuanian", "lt"],
        ["林加拉语", "Lingala", "ln"],
        ["卢干达语", "Luganda", "lg"],
        ["卢克帕语", "Lukpa", "dop"],
        ["卢森堡语", "Luxembourgish", "lb"],
        ["卢旺达语", "Kinyarwanda", "rw"],
        ["罗马尼亚语", "Romanian", "ro"],
        ["罗姆语", "Romani", "rmn"],
        ["马尔加什语", "Malagasy", "mg"],
        ["马耳他语", "Maltese", "mt"],
        ["马恩岛语", "Manx", "gv"],
        ["马拉地语", "Marathi", "mr"],
        ["马拉雅拉姆语", "Malayalam", "ml"],
        ["马来语", "Malay", "ms"],
        ["马里语", "Mari", "mhr"],
        ["马姆语", "Mam", "mam"],
        ["马其顿语", "Macedonian", "mk"],
        ["毛利语", "Maori", "mi"],
        ["蒙古语", "Mongol", "mo"],
        ["蒙古语(西里尔)", "Mongolian(Cyrillic)", "mn"],
        ["孟加拉语", "Bengali", "bn"],
        ["缅甸语", "Burmese", "my"],
        ["纳瓦特尔语", "Nahuatl", "nhg"],
        ["南非荷兰语", "Afrikaans", "af"],
        ["南非科萨语", "Xhosa", "xh"],
        ["南非祖鲁语", "Zulu", "zu"],
        ["尼泊尔语", "Nepali", "ne"],
        ["挪威语", "Norwegian", "no"],
        ["帕皮阿门托语", "Papiamento", "pap"],
        ["派特语", "Paite", "pck"],
        ["旁遮普语", "Punjabi", "pa"],
        ["葡萄牙语", "Portuguese", "pt"],
        ["普什图语", "Pashto", "ps"],
        ["齐切瓦语", "Chewa", "ny"],
        ["契维语", "Twi", "tw"],
        ["切诺基语", "Cherokee", "chr"],
        ["日语", "Japanese", "ja"],
        ["瑞典语", "Swedish", "sv"],
        ["萨摩亚语", "Samoan", "sm"],
        ["塞尔维亚语", "Serbian", "sr"],
        ["塞舌尔克里奥尔语", "Seychelles Creole", "crs"],
        ["塞索托语", "Sesotho", "st"],
        ["桑戈语", "Sango", "sg"],
        ["僧伽罗语", "Sinhalese", "si"],
        ["山地马里语", "Hill Mari", "mrj"],
        ["世界语", "Esperanto", "eo"],
        ["舒阿尔语", "Shuar", "jiv"],
        ["斯洛伐克语", "Slovak", "sk"],
        ["斯洛文尼亚语", "Slovenian", "sl"],
        ["斯瓦希里语", "Swahili", "sw"],
        ["苏格兰盖尔语", "Scottish Gaelic", "gd"],
        ["索马里语", "Somali", "so"],
        ["塔吉克语", "Tajik", "tg"],
        ["塔希提语", "Tahitian", "ty"],
        ["泰卢固语", "Telugu", "te"],
        ["泰米尔语", "Tamil", "ta"],
        ["泰语", "Thai", "th"],
        ["汤加语", "Tongan", "to"],
        ["提格雷语", "Tigre", "tig"],
        ["图阿雷格语", "Tamajaq", "tmh"],
        ["土耳其语", "Turkish", "tr"],
        ["土库曼语", "Turkmen", "tk"],
        ["瓦哈卡语", "Chinantec", "chq"],
        ["瓦拉莫语", "Wolaytta", "wal"],
        ["瓦瑞语", "Waray", "war"],
        ["维吾尔语", "Uyghur", "uy"],
        ["威尔士语", "Welsh", "cy"],
        ["文达语", "Venda", "ve"],
        ["沃洛夫语", "Wolof", "wol"],
        ["乌德穆尔特语", "Udmurt", "udm"],
        ["乌尔都语", "Urdu", "ur"],
        ["乌克兰语", "Ukrainian", "uk"],
        ["乌兹别克语", "Uzbek", "uz"],
        ["乌玛语", "Uma", "ppk"],
        ["乌斯潘坦语", "Uspanteco", "usp"],
        ["西班牙语", "Spanish", "es"],
        ["希伯来语", "Hebrew", "he"],
        ["希尔哈语", "Tachelhit", "shi"],
        ["希腊语", "Greek", "el"],
        ["夏威夷语", "Hawaiian", "haw"],
        ["信德语", "Sindhi", "sd"],
        ["匈牙利语", "Hungarian", "hu"],
        ["修纳语", "Shona", "sn"],
        ["宿务语", "Cebuano", "ceb"],
        ["叙利亚语", "Syriac", "syc"],
        ["亚美尼亚语", "Armenian", "hy"],
        ["雅加达语", "Jakalteko", "jac"],
        ["亚齐语", "Aceh", "ace"],
        ["伊博语", "Igbo", "ig"],
        ["意大利语", "Italian", "it"],
        ["意第绪语", "Yiddish", "yi"],
        ["彝语", "Yi language", "ii"],
        ["印地语", "Hindi", "hi"],
        ["印尼巽他语", "Sundanese", "su"],
        ["印尼语", "Indonesian", "id"],
        ["印尼爪哇语", "Javanese", "jv"],
        ["英语", "English", "en"],
        ["尤卡坦玛雅语", "Yucatec Maya", "yua"],
        ["约鲁巴语", "Yoruba", "yo"],
        ["越南语", "Vietnamese", "vi"],
        ["粤语", "Cantonese", "yue"],
        ["藏语", "Tibetic", "ti"],
        ["哲尔马语", "Zarma", "dje"],
        ["中文(简体)", "Chinese (Simplified)", "zh"],
        ["中文(繁体)", "Chinese (Traditional)", "cht"],
        ["壮语", "Zhuang language", "za"],
        ["宗喀语", "Dzongkha", "dz"]]

err_msg = {"10000": "输入为空",
           "10001": "请求频繁，超出QPS限制",
           "10003": "请求字符串长度超过限制",
           "10005": "源语编码有问题，非UTF-8",
           "13001": "字符流量不足或者没有访问权限",
           "13002": "apikey参数不可以是空",
           "13003": "内容过滤异常",
           "13007": "语言不支持",
           "13008": "请求处理超时",
           "14001": "分句异常",
           "14002": "分词异常",
           "14003": "后处理异常"}
